from typing import Protocol


class ObjectStorage(Protocol):
    def put(self, key: str, data: bytes) -> None: ...

    def get(self, key: str) -> bytes: ...

    def path_for(self, key: str) -> str: ...
